<?php 
	if($_REQUEST['action']=='dashboard'){
		include("page/dashboard.php");
	}
	if($_REQUEST['action']=='modifymaster'){
		include("page/modifymaster.php");
	}
	if($_REQUEST['action']=='addmaster'){
		include("page/addmaster.php");
	}
	if($_REQUEST['action']=='editmaster'){
		include("page/editmaster.php");
	}
	if($_REQUEST['action']=='actionmaster'){
		include("page/actionmaster.php");
	}
	if($_REQUEST['action']=='returnfromspdib'){
		include("page/returnfromspdib.php");
	}
	if($_REQUEST['action']=='delivered'){
		include("page/delivered.php");
	}
	if($_REQUEST['action']=='datamaster'){
		include("page/datamaster.php");
	}
	if($_REQUEST['action']=='report'){
		include("page/report.php");
	}
	
?>